# Generated automatically from Makefile.in by configure.


SHELL = /bin/sh
srcdir = .
top_srcdir = ../..



MANPAGEFILES = backuplogs.man \
	dumpfile.man \
	dumplist.man \
	passwd_coda.man \
	groups_coda.man \
	maxgroupid.man \
	multicastagents.man \
	multicastgroups.man \
	servers.man \
	user_coda.man \
	volumelist.man \
	vrdb.man \
	vrlist.man \
	vsgdb.man \
	vstab.man \
	vicetab.man

include ../../Makerules
