# Generated automatically from Makefile.in by configure.

SHELL = /bin/sh
srcdir = .
top_srcdir = ../..




MANPAGEFILES = au.man \
               auth2.man \
               authmon.man \
               autobackup.man \
               backup.man \
               bldvldb.man \
               clone.man \
               createvol.man \
               createvol_rep.man \
               fsck-coda.man \
               initpw.man \
	       makeftree.man \
               merge.man \
               norton.man \
               pcfgen.man \
               purgevol.man \
               purgevol_rep.man \
               pwd2pdb.man \
               readdump.man \
               replay.man \
               srv.man \
               startserver.man \
               updateclnt.man \
               updatemon.man \
               updatesrv.man \
               venus.man \
               volutil.man \
               vutil.man

include ../../Makerules
