#!/bin/sh

CFILE=`basename $1`.cntr

if [ -f ${CFILE} ]; then
  rm ${CFILE}
fi

cat > ${CFILE} <<END
<!doctype linuxdoc SYSTEM  [
<!entity content SYSTEM 
END

echo \"$1\" >> ${CFILE}

cat >> ${CFILE} <<END
>
]>

&content;
