# Generated automatically from Makefile.in by configure.

SHELL = /bin/sh
srcdir = .
top_srcdir = ../..


SUBDIRS = 

MANPAGEFILES = cfs.man \
               clearstats.man \
               clog.man \
               cmon.man \
               cpasswd.man \
               ctokens.man \
               cunlog.man \
               dirRepair.man \
               heal.man \
               hoard.man \
               mvdb.man \
	       filcon.man \
               repair.man \
               spy.man \
               ttyfcon.man

include ../../Makerules


